return {
  -- {
  --   'hrsh7th/nvim-cmp',
  --   dependencies = {
  --     'hrsh7th/cmp-buffer',
  --     'hrsh7th/cmp-cmdline',
  --     'hrsh7th/cmp-nvim-lsp',
  --     'hrsh7th/cmp-nvim-lua',
  --     'hrsh7th/cmp-path',
  --     'onsails/lspkind-nvim',
  --     'rafamadriz/friendly-snippets',
  --     'saadparwaiz1/cmp_luasnip',
  --     'L3MON4D3/LuaSnip',
  --   },
  --   config = function()
  --     local cmp = require('cmp')
  --     local lspkind = require('lspkind')
  --     cmp.setup({
  --       snippet = {
  --         expand = function(args)
  --           require('luasnip').lsp_expand(args.body)
  --         end,
  --       },
  --       mapping = {
  --         ['<C-n>'] = cmp.mapping.select_next_item(),
  --         ['<C-p>'] = cmp.mapping.select_prev_item(),
  --         ['<C-b>'] = cmp.mapping.scroll_docs(-4),
  --         ['<C-f>'] = cmp.mapping.scroll_docs(4),
  --         ['<C-Space>'] = cmp.mapping.complete(),
  --         ['<C-e>'] = cmp.mapping.abort(),
  --         ['<C-y>'] = cmp.mapping.confirm({ select = true }),
  --       },
  --       sources = {
  --         { name = 'buffer' },
  --         { name = 'nvim_lsp' },
  --         { name = 'nvim_lua' },
  --         { name = 'path' },
  --         { name = 'luasnip' },
  --       },
  --       formatting = {
  --         format = lspkind.cmp_format({
  --           mode = 'symbol_text',
  --           maxwidth = 50,
  --           ellipsis_char = '...',
  --           menu = {
  --             buffer = '[buf]',
  --             cmdline = '[cmd]',
  --             buffer = '[buf]',
  --             luasnip = '[snip]',
  --             nvim_lsp = '[lsp]',
  --             nvim_lua = '[api]',
  --             path = '[path]',
  --           },
  --         }),
  --       },
  --     })
  --     -- cmp.setup.cmdline('/', {
  --     --   mapping = {
  --     --     cmp.mapping.preset.cmdline(),
  --     --   },
  --     --   sources = cmp.config.sources({
  --     --     { name = 'buffer' },
  --     --   }, {
  --     --     { name = 'cmdline_history' },
  --     --   }),
  --     -- })
  --     -- cmp.setup.cmdline(':', {
  --     --   mapping = {
  --     --     cmp.mapping.preset.cmdline(),
  --     --   },
  --     --   sources = cmp.config.sources({
  --     --     { name = 'path' },
  --     --   }, {
  --     --     { name = 'cmdline' },
  --     --   }, {
  --     --     { name = 'buffer' },
  --     --   }, {
  --     --     { name = 'cmdline_history' },
  --     --   }),
  --     -- })
  --     local ls = require('luasnip')
  --     vim.keymap.set({'i', 's'}, '<C-l>', function() ls.jump(1) end, {silent = true})
  --     vim.keymap.set({'i', 's'}, '<C-h>', function() ls.jump(-1) end, {silent = true})
  --     vim.keymap.set({'i', 's'}, '<C-e>', function()
  --       if ls.choice_active() then
  --         ls.change_choice(1)
  --       end
  --     end, {silent = true})
  --     require('luasnip.loaders.from_vscode').lazy_load()
  --   end,
  -- },
}
